import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Header";
import Footer from "./Footer";


import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App from Main layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  model,
}: Readonly<{
  children: React.ReactNode;
  model: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {model}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
